### ISSUE TITLE
upgrade to next.js 13

### ISSUE THREAD

**Issue by tan-ahmed** [mantinedev/mantine-next-template#25]
would be good to upgrade to latest next.js, there are many improvements

**Comment by rtivital** [comment]
You can upgrade it on your side, change version in package.json and install dependencies

**Comment by tan-ahmed** [comment]
But I don't think it's straight forward, I ran into issues doing this. Hence I am hoping you can update the entire template

**Comment by jhanschoo** [comment]
> But I don't think it's straight forward, I ran into issues doing this. Hence I am hoping you can update the entire template with latest packages. Many thanks

I wasn't able to reproduce actual issues from the template itself with just about all deps updated: check the below `package.json` file. I encountered some peer-deps versioning issues due to `storybook`. If you are migrating your code take note of Next.js's migration guide, and especially `next/image` and `next/link` in https://nextjs.org/blog/next-13#breaking-changes.

Attached a `package.json` with updated deps below. (`jest` still retained at `v27` for linter version compatibiility)

[package.json.txt](https://github.com/mantinedev/mantine-next-template/files/9893000/package.json.txt)

**Comment by tan-ahmed** [comment]
thanks @jhanschoo this is working now. Although I still think the overall template should be updated just to keep things upto date etc

**Comment by reza-ebrahimi** [comment]
Migrating to `next.js 13` introduced new `app` directory and new `special files` introduced. Therefore previous `_app.tsx` and `_document.tsx` files are now replaced with `Layout.tsx` file.

Consider reopening the issue since there are errors on using `mantine` providers after migrating to `next.js 13`.
